### ISSUE TITLE
Column and Row numbers reset to 12 and 9 when the page is refreshed

### ISSUE THREAD

**Issue by cmcrawford2** [cmcrawford2/memory-game#1]
Store the number of rows and columns in local storage, and retrieve them if they exist, upon starting the game or refreshing the browser.

**Comment by cmcrawford2** [comment]
You'll have to know something about React and local storage, but I think a beginner could do this.

**Comment by Sukhendu2002** [comment]
Hey @cmcrawford2, Can you please assign this to me, I want to work on this issue

**Comment by cmcrawford2** [comment]
Done! Thanks!

**Comment by Sukhendu2002** [comment]
Thanks, @cmcrawford2. I am starting to work on this
